### ISSUE TITLE
Peidei

### ISSUE THREAD

**Issue by leonimurilo** [guilherme-otran/projector#21]

**Comment by julia-otran** [comment]
Ahhh fica tranquilo, daqui da onde eu to nem deu pra sentir o cheiro.

Já lavou seu ânus depois disso?

**Comment by julia-otran** [comment]
Em adendo, gostaria de pedir encarecidamente para que você sempre proveja uma descrição ao criar `issues`.
Como nada foi declarado, simplesmente fechei ela.

Espero que você não tenha esquecido de descrever o bug.

Além do mais, computadores são à prova de mau odor, exceto cheiro de queimado, mas nesse caso o software continuará funcionando
